#cloud-config
autoinstall:
  version: 1

  source:
    id: ubuntu-server

  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Madrid

  network:
    version: 2
    ethernets:
      enp3s0:
        dhcp4: true
      eno1:
        dhcp4: true

  identity:
    username: mael
    hostname: servidor_peluqueria_mael
    password:

  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2gRBvsnqbwpeLuys9c6wbWTOQVloh5luRf8JdebjWDjGDyLE4nopSL12a2FIyzRNNsTslYvisv69Sl5cEEbK4ulb7YznypHFTe47vWRXDyBq8jqTzBfdXZ6ZUbPQIKED4Veu1FgX1KzsV6bDHKeG984f6Zc7FRANZkprRYMzl469JzJuGiKzs3pEi1sx/l4WL+s9REyvFUjc41fh83VlrVAjFL3X72/zV0akejFtVIvBtbXZnyu4mQQTaS7E5SQwqFoeSyYIcWBrs74GAluFLDKx1Cr+p8GO2qGu0EpuiHj2jdlV6EiumCkkG85TiipfeWHdsjewKeIQsM9jxvNLOOb5D1HockCiaXO8ZBmk0iIHhOoiP/shDLGFgYgKfb3bt514Q19/w2xpccquf6qaBDZbHs12MxN7luDm2s3S1HXjieHmh4wvQ/I0acD+NnD04SOl2S113xWkPCgABVHDXh59LFNA5c32CMTObfV16pdqJbiVVcIuPsWMadu2ynfPzBeiZ0dkPRRq1agHnKb+9B2ZJkRemHroySgJrs0BRDhb0pclFiBD3ElEgcdculu6x3Oe5VM+AcL7V+1/qQjy4UvWRlrS9756HN0HJy1zjFkeOWGfgm2gtSVVKTtrQWvT2oyPlteD14aqzcdIffGqvfSMWmSKh58+6gf4By4yXSQ== he0780070@gmail.com

  packages:
    - git
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  late-commands:
    - |
      # Add Docker’s official GPG key
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - |
      # Add Docker APT repository
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - |
      # Update package index and install Docker
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io
    - |
      # Enable and start the SSH service
      systemctl enable ssh
      systemctl start ssh

    - docker pull python
    - docker pull redis
    - docker pull mongo
    - docker pull rethinkdb
    - docker pull nvidia/cuda:11.4.3-runtime-ubuntu20.04
  
  shutdown: reboot
  storage:
    config:
      - id: disk-CT1000BX500SSD1
        type: disk
        ptable: gpt
        path: /dev/sda  # Ajustar al dispositivo correcto, /dev/sda en este caso
        wipe: superblock-recursive

      # Partición EFI
      - id: efipart
        type: partition
        device: disk-CT1000BX500SSD1
        offset: 1048576   # 1 MiB
        size: 600M
        flag: boot
        grub_device: true
  
      # Partición /boot
      - id: bootpart
        type: partition
        device: disk-CT1000BX500SSD1
        size: 1G
  
      # Partición raíz /
      - id: rootpart
        type: partition
        device: disk-CT1000BX500SSD1
        size: -1   # Utiliza todo el espacio restante del disco
  
      # Formatear particiones
      - id: efipart-format
        type: format
        volume: efipart
        fstype: fat32
  
      - id: bootpart-format
        type: format
        volume: bootpart
        fstype: ext4
  
      - id: rootpart-format
        type: format
        volume: rootpart
        fstype: ext4
  
      # Montaje de particiones
      - id: efipart-mount
        type: mount
        device: efipart-format
        path: /boot/efi
  
      - id: bootpart-mount
        type: mount
        device: bootpart-format
        path: /boot
  
      - id: rootpart-mount
        type: mount
        device: rootpart-format
        path: /
