

services:
  peluqueriamael_app_api:
    #container_name: deployment_peluqueriamael_app_api
    image: peluqueriamael_app_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../../../../../Backend:/peluqueriamael/Backend
      - ../../../../../../__init__.py:/peluqueriamael/__init__.py
      - ../../../../../../LICENSE:/peluqueriamael/LICENSE
      - ../../../../../../README.md:/peluqueriamael/README.md
    ports:
      - "8000:8000"
    environment:
      - MONGODB_HAIRDRESSER_PASSWORD=example
      - MONGODB_HAIRDRESSER_USERNAME=root
    command: ['./execute.sh']
    networks:
      - db_hairdresser_network
      - deployment_hairdresser_network_cryptoapi
      - tor_network

networks:
  db_hairdresser_network:
    external: true
  deployment_hairdresser_network_cryptoapi:
    external: true
  tor_network:
    external: true