

services:
  tor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
    volumes:
      - tor_data:/etc/tor
    container_name: tor-proxy
    networks:
      - tor_network

networks:
  tor_network:
    driver: bridge

volumes:
  tor_data: