version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hairdresser
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data_hairdresser:/data/db
    ports:
      - "27017:27017"

  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb_hairdresser
    restart: always
    volumes:
      - rethink_data_hairdresser:/data
    ports:
      - "8080:8080"     # Admin console
      - "28015:28015"   # Driver port
      - "29015:29015"   # Cluster port

  redis:
    image: redis:latest
    container_name: redis_hairdresser
    restart: always
    volumes:
      - redis_data_hairdresser:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo_data_hairdresser:
  rethink_data_hairdresser:
  redis_data_hairdresser:
